name: Deploy Backend → Render

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  desplegar-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Notificar a Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
